#! python3
# Generates initial sheet-- useless
import openpyxl
from os import startfile
import pickle

C = 5
S = [3,2,3,4,3]
A = 10+1

wb = openpyxl.Workbook()
ws = wb.active

r = 1
gap = 2
for i in range(1,C+1):
	for j in range(1,A+1):
		ws.cell(row = r, column = j+1).value = "A " + str(j)
		ws.cell(row = r, column = j+1).font = openpyxl.styles.Font(bold=True)
	for j in range(A+1,A+S[i-1]+1):
		ws.cell(row = r, column = j+1).value = "C " + str(i) +" S " + str(j-A)
		ws.cell(row = r, column = j+1).font = openpyxl.styles.Font(bold=True)

	for k in range(1,S[i-1]+1):
		ws.cell(row = r+k, column = 1).value = "C " + str(i) + " S " + str(k)
		ws.cell(row = r+k, column = 1).font =openpyxl.styles.Font(bold=True)

	r = r + (S[i-1]+1+gap)


INV = [("M3","N2"),("M4","O2"),("N4","O3"),("M9","N8"),("M14","N13"),("M15","O13"),("N15","O14")]
INV = INV + [("M20","N19"),("M21","O19"),("M22","P19"),("N21","O20"),("N22","P20"),("O22","P21")]
INV = INV + [("M27","N26"),("M28","O26"),("N28","O27")]
for i,j in INV:
	ws[i].value = "INV"

pickle.dump(INV, open("log.p","wb"))
wb.save("s10.xlsx")
startfile("s10.xlsx")
